/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ccalljava_JNI */

#ifndef _Included_com_example_ccalljava_JNI
#define _Included_com_example_ccalljava_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ccalljava_JNI
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ccalljava_JNI_callbackAdd
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ccalljava_JNI
 * Method:    callbackHelloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ccalljava_JNI_callbackHelloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ccalljava_JNI
 * Method:    callbackPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ccalljava_JNI_callbackPrintString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ccalljava_JNI
 * Method:    callbackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ccalljava_JNI_callbackSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
